### PR TITLE
Selenide support for PageObjects without @FindBy annotations

### PR DESCRIPTION
**Pull request by SergeyPirogov**
This PR fixes problem with initialization PageObjects that have SelenideElements declared as Class fields. See example below:

class StartPage{
     private SelenideElement startPage = $("#start-page");
}

Before fix, if we use Selenide methods open("url",Class) or page(class) Selenide ignored field initialization and tried to find element by ID or Name of class field.

### CODE REVIEW

**Comment by asolntsev** [comment]
@SergeyPirogov Next time please add tests too!
See https://github.com/codeborne/selenide/commit/8bc9f0cc52f0dba488842d3ffb5ca85c7da0a282

**Comment by SergeyPirogov** [comment]
@asolntsev I had tests included in pull requests

**Comment by SergeyPirogov** [comment]
https://github.com/codeborne/selenide/blob/fa4caf8dbe527533ab69e222022e0a5128311de6/src/test/java/integration/SelenidePageFactoryTest.java

**Comment by asolntsev** [comment]
@SergeyPirogov Thank you! We recently released Selenide 4.2.1 that contains this improvement.

**Comment by CaBocuk** [comment]
It seems not working in case if we have SelenideElement inside ElementsContainer which is declared in some page object class

For example I have the following code:
```
public class AdminHeader extends ElementsContainer {
	private SelenideElement newEventButton = $(".new-event-button");
}
```

```
public class AdminHomePage {
	@FindBy(css=".navigation-header")
	AdminHeader header;
}
```

And after calling _page(AdminHomePage.class)_ I receive following error


```
Element not found {by id or name "newEventButton"} 
Expected: visible
Timeout: 4 s.
Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"name","selector":"newEventButton"} 	
at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:31) 	
at com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:82) 	
at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:59) 	
at com.codeborne.selenide.commands.Should.should(Should.java:35) 	
at com.codeborne.selenide.commands.Should.execute(Should.java:29) 	
at com.codeborne.selenide.commands.Should.execute(Should.java:12) 	
at com.codeborne.selenide.commands.Commands.execute(Commands.java:143) 	
at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:87) 	
at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63) 	
at com.sun.proxy.$Proxy29.shouldBe(Unknown Source) 	
at com.epam.events.admin.steps.ContainsAdminHeaderSteps.openNewEventPopup(ContainsAdminHeaderSteps.java:11) ............
--
```

**Comment by BorisOsipov** [comment]
@CaBocuk It works in selenide tests https://github.com/codeborne/selenide/blob/fa4caf8dbe527533ab69e222022e0a5128311de6/src/test/java/integration/PageObjectTest.java

If you ran into issue create reproducible example and report it https://github.com/codeborne/selenide/issues/new

Do not write comments to closed PR's.
We can miss such messages.

**Pull request merged**
