### PR TITLE
Pull request to close Issue 758.

### PR DESCRIPTION
**Pull request by YuriIvanov**
New version of download method added. Now we are able download files using custom timeout.

## Proposed changes
I've added new version of SelenideElement.download(long) method to give users ability to use custom timeout for each separate file download.
Closes https://github.com/codeborne/selenide/issues/758

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by rosolko** [comment]
@YuriIvanov Thanks for PR. For general - can you please add tests that prove this feature?

**Comment by YuriIvanov** [comment]
I think i can add a couple of tests to **DownloadFileWithProxyServerTest** and **FileDownloadViaHttpGetTest** test classes to verify that download with custom timeout will take no more than this timeout. But first i need to investigate how to use Mockito and JUnit, never used them before :) So not today, likely tomorrow.

**Comment by asolntsev** [comment]
@YuriIvanov Next time please check that `./gradlew check test` is OK. This time I merged the PR and fixed checkstyle issue by myself. Thank you.

**Comment by YuriIvanov** [comment]
@asolntsev This command told me only about errors like "no newline at the end of the file" for files that i didn't even touch.

**Pull request merged**
