### PR TITLE
Fixed bug with IE and basic auth

### PR DESCRIPTION
**Pull request by simple-elf**
Problem mentioned in #366 and highlighted in #320.
So here is quick fix of that. I think if there is empty login parameter we don't need to handling alert for basic auth.

### CODE REVIEW

**Comment by anilreddy** [comment]
@simple-elf Thanks for the quick fix :-)

**Comment by simple-elf** [comment]
Sorry for commit spam, I'm new on github =)

**Comment by anilreddy** [comment]
@simple-elf also can you add a test-case for it.

**Comment by asolntsev** [comment]
@simple-elf Thank you for the fix.

NB! Why do you think that this is "quick fix" Do you think that it's a "dirty temporary solution"? Do you have an idea of f better solution?

**Comment by asolntsev** [comment]
@simple-elf @anilreddy I have merged the fix and released selenide 3.8.1
It will appear in maven central repo in few hours.

**Comment by simple-elf** [comment]
We need to test not only this fix, but all code in IE too, but it's hard to find such service for IE. Maybe SauceLabs? I need to investigate it.

**Comment by simple-elf** [comment]
Test shoul be smth like this
```
  @Test
  public void canPassWithoutBasicAuthInIe() {
    assumeTrue(isIE());
    Selenide.open("http://httpbin.org/get");
    assertThat(source(), containsString("\"url\": \"http://httpbin.org/get\"")); // "": ""
  }
```

**Comment by asolntsev** [comment]
+1
Actually we need a VPS with Windows. Because we need to 
1) run Selenide tests in IE, and
2) build NSelenide - selenide port to .NET

Don't you know a good and cheap Windows hosting?

**Comment by simple-elf** [comment]
For running tests in IE we probably can use SauceLabs, it has free VM's for open source projects with IE

**Comment by simple-elf** [comment]
@anilreddy 3.8.1 already in maven
https://mvnrepository.com/artifact/com.codeborne/selenide/3.8.1

**Comment by anilreddy** [comment]
@simple-elf yeah am already using it.

**Pull request merged**
