### PR TITLE
Browser capabilities configuration section added

### PR DESCRIPTION
**Pull request by SergeyPirogov**
Need to add merge for chrome and firefox capabilities !!!

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
Changes from this PR will help people to set custom capabilities for custom Chrome options or Firefox profies and avoid people adding PR's such as this one https://github.com/codeborne/selenide/pull/546/files

**Comment by asolntsev** [comment]
@SergeyPirogov This PR has conflicts with master branch. Could you resolve it?

**Comment by taeunChoi** [comment]
Is this feature added to the release version?

**Comment by asolntsev** [comment]
@taeunChoi This PR is not merged yet. We need to resolve conflicts first.

**Comment by asolntsev** [comment]
@SergeyPirogov This PR has conflicts with master branch. Could you resolve it?

**Comment by SergeyPirogov** [comment]
@asolntsev Webdriverfactory were rewritten and now as I understand logic splitted to DriverFactories. So it will take some time to fix this PR

**Comment by BorisOsipov** [comment]
It was rewritten in https://github.com/codeborne/selenide/pull/664

**Pull request closed without merging**
