### PR TITLE
Implement #196 Add file downloading mechanism without "href"

### PR DESCRIPTION
**Pull request by dimand58**
@asolntsev please review first version of implementation #196 issue.

How to use in end-user projects:
```java
        Selenide.prepareDownload("C:\\SomeFolder", "", "application/x-sdlc");
        WebDriverRunner.getWebDriver().get("http://javadl.sun.com/webapps/download/AutoDL?BundleId=113227");
        // Downloaded file with name chromeinstall-8u66.exe
        File tmp = new File(Selenide.$(By.tagName("body")).getText());
```
or
```java
        Selenide.prepareDownload("C:\\SomeFolder","SomeFile.exe","application/x-sdlc");
        WebDriverRunner.getWebDriver().get("http://javadl.sun.com/webapps/download/AutoDL?BundleId=113227");
        // Downloaded file with name SomeFile.exe
        File tmp = new File(Selenide.$(By.tagName("body")).getText());
```
or
```java
        Selenide.$(By.id("button_for_file_download_after_click"))
                .prepareDownload("C:\\SomeFolder", "", "application/pdf")
                .click();
        File tmp = new File(Selenide.$(By.tagName("body")).getText());
```

TODO:
1) Review
2) Some tests
3) Merge conflicts

### CODE REVIEW

**Comment by dimand58** [comment]
Fix

**Comment by asolntsev** [comment]
@dimand58 Thank you! Great! It's almost what we need.

The only problem is the API. The new downloading mechanism is particularly needed in situation when we don't know exact URL. You typically fill some form with 100500 fields, click "submit", and file starts downloading. 

Try for example:
* http://idemo.bspb.ru/#corporate
* Cards -> Acquiring -> "View terminals"
* Put some checkboxes and click "Report"
* Expected result: an XLS file starts downloading

I suggest to make existing method `$.download()` more powerful without adding any new methods.

This method:
```java
  File report = $("button").download();
```

currently only works with elements `<a href=***>`.
What I suggest is to make it work with any downloads. It could work like this:

1. Test calls `$("button").download();`
2. Selenide sets some ThreadLocal flag like `Selenide.browserMobProxyActive.set(true);`
3. Selenide clicks the `button`
4. Because of flag, BMP stores all received files to some folder.
5. Selenide method `download` returns first of these files.
6. Selenide method `download` resets flag back: `Selenide.browserMobProxyActive.set(false);`
7. While this flag is `false`, BMP does not store any files (to avoid degrading performance).

**Comment by dimand58** [comment]
@asolntsev 2 problem exists:
1) BrowserMob must be activated BEFORE of WebDriver instance
2) Web must know ALL mime types for files

**Comment by asolntsev** [comment]
@dimand58 
1) BrowserMob must be activated BEFORE of WebDriver instance
Yes, but it's not a problem. Selenide will activate BrowserMob in the very beginning (before creating webdriver). But this BrowserMob instance will not save any files. It will just proxy requests from webdriver to server. Then, method `$.download()` will set some internal flag to TRUE, and only then BrowserMob will save all responses with header like "attachment" to local files.

2) Web must know ALL mime types for files
I suggest that Selenide can return the first saved file with header like "attachment".

With your implementation, use needs to know the exact URL for downloading file. But user cannot always know it. For example, file can be downloaded as a result of form submission.

**Comment by dimand58** [comment]
OK.
Response filter will be save file if HTTP response header have "Content-Disposition: attachment;". In this case no need to know MIME type of downloaded file.

But what about redirections?
Test case:
1) Go to http://www.java.com/ru/download/chrome.jsp
2) Click on BIG RED BUTTON (java dowload)

Actual:
1) No Content-Disposition in response header
2) 1 redirect occured (to http://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u66-b18/chromeinstall-8u66.exe)
3) AGAIN - no Content-Disposition in response header

**Comment by mplushnikov** [comment]
+1 for downloading files from elements without href attribute, like buttons.

**Comment by asolntsev** [comment]
@mplushnikov agree. We need this. I will work on it soon.

**Comment by asolntsev** [comment]
@dimand58 Sorry for the long delay. I am almost ready to merge the pull request, but I have one problem.

BMP doesn't work for me when I run tests locally (against http://127.0.0.1:9000). But it works for remote sites like google.com. Don't you know a solution?

**Comment by dimand58** [comment]
@asolntsev , hi!
Give me a few days, I will try to solve this problem.

**Comment by dimand58** [comment]
@asolntsev 
Are you tried to use DNS name of your PC  instead of 127.0.0.1 ? I suppose that this trick can help

**Comment by asolntsev** [comment]
How can I use name of computer? I cannot hardcode it in tests - tests
should be easily runnable on any machine.

**Comment by dimand58** [comment]
You can get current pc name in code, via some method maybe

**Comment by asolntsev** [comment]
Yes, something like InternetAddress.getLocal().getHost() should return name
of current computer. But it can be very slow, depending on network
configuration.

Why couldn't BMP just work with IP? Both Jetty an Netty can.

**Comment by dimand58** [comment]
@asolntsev What does happen when your test opens http://127.0.0.1:9000 via proxy?
I tried on my PC and all works great.

**Comment by asolntsev** [comment]
This is my case that does not work:
1. open http://127.0.0.1:9000 via proxy
2. download a file

Result: proxy intercepts all requests, but does not intercept server
response. So I cannot get the downloaded file.
Expected result: I want to get server response.


Andrei Solntsev

2016-04-22 19:03 GMT+03:00 Demin Dmitrii <notifications@github.com>:

**Comment by dimand58** [comment]
@asolntsev strange...
My steps:
1) Init BMP before first WD creation
 ```
BrowserMobProxy proxy = new BrowserMobProxyServer();
 {
     proxy.start(1234);
     Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
     WebDriverRunner.setProxy(seleniumProxy);
 }
```
2) Add filter before URL opening:
`proxy.addResponseFilter(new ResponseFilterImpl());`
3) Open URL:
`Selenide.open("http://127.0.0.1");`
4) In debug mode I can see call of filterResponse method in ResponseFilterImpl

**Comment by dimand58** [comment]
Browser - Google Chrome
BMP:
```
<dependency>
        <groupId>net.lightbody.bmp</groupId>
        <artifactId>browsermob-core-littleproxy</artifactId>
        <version>2.1.0-beta-5</version>
</dependency>
```

**Comment by asolntsev** [comment]
@dimand58 Please review my failing test. In Selenide master branch, there are 2 tests:
* `integration.proxy.BrowserMobProxyTest` - it uses deprecated `net.lightbody.bmp.proxy.ProxyServer` - and it works
* `integration.proxy.BrowserMobProxyServerTest` - it uses newer `net.lightbody.bmp.BrowserMobProxyServer` - and it doesn't work for localhost. Please take a look at test  `local_https()` that is currently ignored. 

@dimand58 Can you say why this test fails?

**Comment by dimand58** [comment]
@asolntsev , got it. I will investigate this test at evening today

**Comment by dimand58** [comment]
@asolntsev can you update your certificate? It can be one of reason of current problem. 
image

**Comment by asolntsev** [comment]
Do you mean the SSL certificate of https://localhost:xxxx?

I deliberately use self-signed (untrusted) SSL certificate there because I
want to test how Selenide works with untrusted certs. It's because many
companies use untrusted certs on their test-servers.

Typically webdrivers have method like "setTrustCerts(true)", I guess BMP
also has such a method.

Andrei Solntsev

2016-04-25 17:57 GMT+03:00 Dmitriy Demin <notifications@github.com>:

**Comment by dimand58** [comment]
I created new self-signed cert (with valid expiration date and from/to fields 127.0.0.1) but problem still exists. 
**However, in IE11 page opens via proxy!** I'm totaly confused

**Comment by dimand58** [comment]
@asolntsev 
I've found and checked the solution - we should use latest version of BPM (beta-7-SNAPSHOT which not realised yet). With that BMP version local web works good.
I guess we should to wait a little bit

**Comment by asolntsev** [comment]
@dimand58 I implemented this idea a little bit differently in Selenide 3.9

Huge thanks for your ideas and support!

**Pull request closed without merging**
