### PR TITLE
#695 Do not open a browser if `Configuration.reopenBrowserOnFail` is …

### PR DESCRIPTION
**Pull request by asolntsev**
…`false` and user has not set webdriver manually

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
@asolntsev Do you take into account such changes will break tests for users who accidentally still use `reopenBrowserOnFail=true`?

**Comment by asolntsev** [comment]
@BorisOsipov Why? `reopenBrowserOnFail` is `true` by default. Nothing will change in this case.

**Comment by BorisOsipov** [comment]
I've misprinted. If someone accidentally have been setted reopenBrowserOnFail=false.

**Comment by asolntsev** [comment]
@BorisOsipov Yes, right, in this case the behaviour will change. The browser will not start. It's ok for me. The test will fail with a clear error message:

```
java.lang.IllegalStateException: No webdriver is bound to current thread: 1, and cannot create a new webdriver because Configuration.reopenBrowserOnFail=false
```

**Pull request merged**
