### PR TITLE
#675: Chrome browser gets maximized

### PR DESCRIPTION
**Pull request by tbgdn**
## Proposed changes
Fix for #675 issue.

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by user667** [comment]
Pretty sure this solution will not solve the issue I'm seeing at the moment:
```bash
WARNING: Cannot maximize RemoteWebDriver: org.openqa.selenium.WebDriverException:
    unknown error: failed to change window state to maximized, current state is normal
```
Seems related to [SeleniumHQ/docker-selenium#559](https://github.com/SeleniumHQ/docker-selenium/issues/559).

Possible solution is using a DesiredCapabilities profile for Chrome.

**Comment by BorisOsipov** [comment]
>Pretty sure this solution will not solve the issue I'm seeing at the moment:

Unquestionably! And I know why - this PR for issue https://github.com/codeborne/selenide/issues/675 and it doesn't try to solve problem you are ran into.

**Comment by user667** [comment]
Yes indeed. I only quickly scanned through the issues - I'm new to Selenide. Would it make sense to create an issue for that problem?

**Comment by BorisOsipov** [comment]
@user667 I think if your run chrome in docker you have to specify window size explicitly.

**Comment by asolntsev** [comment]
@BorisOsipov @user667 I strongly recommend to **always** set browser size explicitly and never use `startMaximized`.

**Comment by asolntsev** [comment]
@tbgdn Thank you!
However, `driver.manage().window().maximize()` doesn't work for Chrome. At least on my MacBook, it doesn't throw exceptions but also doesn't maximize the Chrome window.

**Comment by user667** [comment]
Thanks for the hints @BorisOsipov and @asolntsev and @tbgdn for the PR. I'm sure we can bypass the "issue" for the time being.

However I wanted to try the recommended workaround by passing custom desired capabilities but as far as I understand I'm depending on [Browser capabilities configuration section added #556](https://github.com/codeborne/selenide/pull/556). Therefore I'll try version 4.10 or 4.10.01 asap.

```java
ChromeOptions options = new ChromeOptions();
options.addArguments("--start-maximized");
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
capabilities.setCapability(ChromeOptions.CAPABILITY, options);
```
See https://stackoverflow.com/a/9942198

**Comment by asolntsev** [comment]
@user667 What should we do with this PR?
As I understand, it will not help because `driver.manage().window().maximize()` doesn't maximize the Chrome, and doesn't throw any exceptions. Thus method `maximizeBrowser(WebDriver driver)` will never maximize chrome window. 

Should we close this PR?

**Comment by BorisOsipov** [comment]
@asolntsev @tbgdn yes we should.
See my comment in https://github.com/codeborne/selenide/pull/680#issuecomment-375850395

**Pull request closed without merging**
