### PR TITLE
#672 fix lazy evaluation of page objects fields...

### PR DESCRIPTION
**Pull request by asolntsev**
… declared as `$$().get(index)`

to achieve that, I added method `WebElementsCollection.getElements()`
and made some of `WebElementsCollection` implementations cache the result of `getActualElements()`.

it allowed me to remove field `actualElements` from `ElementsCollection`, `CollectionElement`, `SelenideElementIterator`.
Thus method `ElementsCollection.get(index)` doesn't need to load the collection immediately, but just returns a "proxy" - `CollectionElement`.

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
Restart travice due error

**Comment by BorisOsipov** [comment]
Some technical issues on travise today https://www.traviscistatus.com/

**Comment by vinogradoff** [comment]
LazyEvaluationTest added, which still fails. 

Hope it helps in fixing...

**Comment by BorisOsipov** [comment]
>LazyEvaluationTest added, which still fails.

Btw does test pass on 4.9?

**Pull request merged**
