### PR TITLE
Closes #551 Method `$.setValue()` should not fail if it could not tri…

### LINKED ISSUE #551: Method `$.setValue()` should not fail
.. if it could not trigger `change` event (for whatever reason).

Currently method `$.setValue()` does the following:
1. `element.clear();`
2. `element.sendKeys(text);`
3. trigger JS event `change`

If the latter fails, the whole `$.setValue()` fails. But it's not always reasonable. For example, step 3 could fail if webdriver doesn't support javascript.

### PR DESCRIPTION
**Pull request by asolntsev**
…gger change event (for whatever reason).

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
Have never faced such problem

**Comment by asolntsev** [comment]
Me too. :)

**Comment by SergeyPirogov** [comment]
So what is the reason? Just fail fast and not wait for the timeout?

**Comment by asolntsev** [comment]
No, it's not "fail fast". Method will **not** fail in this case.

The reason is rather theoretical: it's **possible** that it happens, and method `setValue()` **should not fail** in this case.

**Pull request merged**
