### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by azakordonets**
I think you guys are doing a great work and I wanted to help somehow. Since I'm not that good familiar with the internals of Selenide, I decided to look it up a bit closer and while doing this I decided to add couple unit tests to increase the test coverage. I didn't change any functionality, but test coverage should increase quite well. Hope you'll accept it fast.

### CODE REVIEW

**Comment by vinogradoff** [comment]
It looks like you have failing tests... 

https://travis-ci.org/codeborne/selenide/builds/234520094?utm_source=github_status&utm_medium=notification

**Comment by azakordonets** [comment]
@vinogradoff yeah, true. For some reason, i don't have this error when i run same `./gradle clean check test chrome htmlunit --info` command on my machine. It looks like i have same errors happening on 2 pull requests and i haven't figured out yet, what's causing it. Will try to investigate it later. If you have any suggestiosn or tips - that would be great

**Comment by asolntsev** [comment]
@azakordonets Wow! You are great!
Unfortunately these tests randomly fail - depending on order of tests.
For example, `CollectionElementByConditionTest` fails if it's executed after `SelenideElementProxyTest` - because the latter sets the static variable: `WebDriverRunner.setWebDriver(webdriver);` and doesn't reset it. 

I have committed a fix in master branch.
Please rebase on master - it should be fix failing tests in your PR.

**Comment by azakordonets** [comment]
@asolntsev thansk a lot :) Will try to do that today in the evening

**Comment by azakordonets** [comment]
I tried to squash all commits and rebase on master, but my git skills failed me and it looks like that i included my another pull request into this pull request as well. Should i revert history somehow, or what is the best way to fix it ?

**Comment by asolntsev** [comment]
@azakordonets Shit happens! Every GIT user had experienced it.  :)

Yes, we need to get a branch with a correct content somehow.
You can create a new branch or pull request if it's easy for you.

**Comment by asolntsev** [comment]
@azakordonets Hi! I created a branch in Selenide repository and copied (aka "cherry-picked") all your commits to it. Please verify if it contains all your changes. If so, we could create PR from this branch.

https://github.com/codeborne/selenide/tree/unit-tests

**Comment by asolntsev** [comment]
Replaced by https://github.com/codeborne/selenide/pull/539 due to merging problems.

**Pull request closed without merging**
