### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by asolntsev**
This is rebased PR https://github.com/codeborne/selenide/pull/537

(all commits are copied from PR https://github.com/codeborne/selenide/pull/537 to this branch)

### CODE REVIEW

**Comment by asolntsev** [comment]
@azakordonets Does this PR contain all your changes?

**Comment by azakordonets** [comment]
@asolntsev yeah looks like for unit tests it's all there :) Sorry, i couldn't figure out yesterday how to rebase properly. For some reason Git looks too complicated for me sometimes. The test coverage increased only for 1 % ( i was hoping to have more) . If you don't mind i would like in the future to add more coverage from time to time, if that will help you guys.

**Comment by asolntsev** [comment]
@azakordonets Sorry, I have updated some of your tests. :)
Just to simplify code.
Going to merge it soon.

**Comment by azakordonets** [comment]
No worries :) I'm glad i could help you guys with that. I will try to add more unit tests in the future . Frankly i was hoping that test coverage will raise much more  but +0.9 is not bad for the first time as well :)

**Pull request merged**
