### PR TITLE
Add command to scroll into view related to #649

### PR DESCRIPTION
**Pull request by rosolko**
## Proposed changes
Add command to scroll into view related to #649

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
@rosolko Thank you for pull request. It has awesome documentation.

P.S. For future, please, separate functional changes and fixing unrelated formatting issues.

**Comment by rosolko** [comment]
@BorisOsipov Sorry about formatting. I've added local `.editorconfig` and it perform trim whitespaces and insert newline at the file end automatically on file save.

**Comment by BorisOsipov** [comment]
@rosolko no problems :). 

Btw Is it good `.editorconfig`? I mean is it suitable for project code style? Maybe we can commit it and use?

**Comment by rosolko** [comment]
@BorisOsipov 
From my point this file is must have. 
It automatically do a lot of work for me.
For example I'm using 4 space indent at most of the project but here 2 space is a standard, but this file can avoid all problem and do a lot of dirty work for me.
For example, locally I'm using this config to match project code style:
```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```
I can create PR with this file and perform code reformat related to style.

**Comment by BorisOsipov** [comment]
Yeah I know what editorconf does.
> perform code reformat related to style.
It will produce huge reformatting changes. I will create issue and think about how we can do it easier.
Thank you for this idea!

**Comment by BorisOsipov** [comment]
@asolntsev yes

**Comment by BorisOsipov** [comment]
@rosolko Thank you

**Pull request merged**
