### PR TITLE
Fix for prompt() in HtmlUnit + new test with default value

### PR DESCRIPTION
**Pull request by simple-elf**
## Proposed changes
Fix HtmlUnit issues in PR #591

Also changed method supportsModalDialogs() from [WebDriverRunner.java](https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/WebDriverRunner.java), because now HtmlUnit 2.27 supports both alert() and prompt()

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by simple-elf** [comment]
Нужно ли менять описание методов confirm и prompt на тему того, что в HtmlUnit теперь работает?

**Comment by asolntsev** [comment]
@simple-elf Yes, we need to update the description of methods confirm() and prompt().

**Comment by asolntsev** [comment]
@simple-elf `integration.ConfirmTest` is broken. Can you fix it?

**Comment by simple-elf** [comment]
In HtmlUnit version 2.28 some tests works, and some doesn't. HtmlUnit can handle alert and prompt, but not confirm.

**Comment by simple-elf** [comment]
Create PR https://github.com/SeleniumHQ/htmlunit-driver/pull/62 for fix confirm handler. So we need to wait this fix.

**Comment by simple-elf** [comment]
Error in test method userCanAddAnyCustomCommandsToSelenide() [CustomCommandsTest.java](https://github.com/codeborne/selenide/blob/master/src/test/java/integration/customcommands/CustomCommandsTest.java)

**Comment by simple-elf** [comment]
There is new release for htmlunit-driver [2.28.1](https://github.com/SeleniumHQ/htmlunit-driver/releases/tag/2.28.1)

**Comment by simple-elf** [comment]
PR is complete, ping @asolntsev

**Comment by BorisOsipov** [comment]
@simple-elf you are trying to merge 88 commits. Almost all of them have already merged to master. Please fix it.
Also please squash your commits. Commits like 
- remove unused imports in AlertTest
- remove unused imports in AlertTest
with changes in one line does't make sense.

Thank you in advance

**Comment by simple-elf** [comment]
Only one way to fix this garbage commits - create new PR https://github.com/codeborne/selenide/pull/634

**Pull request closed without merging**
