### PR TITLE
setSelected method should check value after .click() action #520

### PR DESCRIPTION
**Pull request by jane-ryabchenko**
Added SetSelected.isSelectable and SetSelected.isDeselectable methods.
If user tries to select not selectable element InvalidStateException will be thrown.
If user tries to de-select radio or option element InvalidStateException will be thrown.
Added Unit and Integration tests to cover every case.

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
Well, guys with modern UI frameworks it's all useless!

**Comment by jane-ryabchenko** [comment]
@SergeyPirogov did you mean that this pull request will never be reviewed/merged ?

**Comment by asolntsev** [comment]
@jane-ryabchenko Not exactly :)

But yes, it's true: I am in doubt. I am afraid that this change will make things slower, but will not always solve the problem. I don't claim that your PR is definitely wrong, I am just in doubt. 


Anyway, let's start with a simple question: 
1. What problem are you trying to solve? What is the real case?
2. Why your change doesn't correspond to the title? Title says "setSelected method should check value AFTER .click() action", but actually it checks something else (type, not value) and BEFORE action.

**Comment by jane-ryabchenko** [comment]
@asolntsev 
I'll start with second question.

2) Required change described in #520 doesn't makes much sense to me.
What is the point of reckless clicking of the element and checking if it was right element in right state after click?

1) For example, if I call checkbox.setSelected(true) I expect that  checkbox.isSelected() will return true after the call. But actual code in setSelected method does not checks the state of the element to determine if it's already selected and shouldn't be clicked. Definitely I don't want to be in a situation when checkbox is already selected and call checkbox.setSelected(true) sets selection to false.

**Comment by rosolko** [comment]
@jane-ryabchenko, @asolntsev, @BorisOsipov I my point of view this case mix functionality with verification.
I think the real use case will we:
1. Set selected.
2. Make assert that check condition.
3. You decide check or not.
4. No performance issues.
Are you agree?
So If yes - we can close this PR and check such cases on your side.

**Comment by BorisOsipov** [comment]
First, I don't understand what changes are proposed to this PR - diff is so big and full of garbage. I guess it makes sense to create a new PR with corresponding commits.

Second, I agree with @SergeyPirogov "Well, guys with modern UI frameworks it's all useless!" - it is the sad truth. In modern UI frameworks you hardly ever deal with standard html select.

**Comment by rosolko** [comment]
Close it for now, if really needed submit a new PR cleared from not necessary files.

**Pull request closed without merging**
