### PR TITLE
Added because method to CollectionCondition(#440)

### PR DESCRIPTION
**Pull request by sidelnikovmike**
See #440.
WIP

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `фд` command
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sidelnikovmike** [comment]
@asolntsev any ideas?

**Comment by asolntsev** [comment]
@sidelnikovmike I need time to think about it...

**Comment by sidelnikovmike** [comment]
@asolntsev you are welcome 👍

**Comment by asolntsev** [comment]
@sidelnikovmike Sorry for the delay. It seems that the simplest solution would be to move `because` method inside `CollectionCondition`. See my commit: https://github.com/codeborne/selenide/commit/40effdb53cee3088c00ee55306fe2cf53eebc283

What do you think?

**Comment by asolntsev** [comment]
@sidelnikovmike No problems. I have merged your PR and then my commit. Will be released in Selenide 4.12.2

**Pull request merged**
