### PR TITLE
Implement methods $x(), $$x() witch can find elements via By.xpath 

### PR DESCRIPTION
**Pull request by rmarinsky**
I think I need to add some more tests
And what about interface SelenideElement? Need to add $x and $$x methtods to interface SelenideElement?

### CODE REVIEW

**Comment by SergeyPirogov** [comment]
I think for SelenideElement there should not be $x()

**Comment by rmarinsky** [comment]
Maybe need to add tests for methods $x $$x similar to tests in 'integration.errormessages' packaage?
https://yadi.sk/i/zLWBt27u3G848x

**Comment by asolntsev** [comment]
I don't understand why this PR is red on Travis CI.
As to me, everything looks good. Going to merge it.

**Comment by SergeyPirogov** [comment]
Yeee, wait for release with this feature ;)

**Pull request merged**
