### PR TITLE
Fix #655"Listeners SoftAsserts: Screenshot: null for FAIL test"

### LINKED ISSUE #655: Listeners  SoftAsserts:   Screenshot: null   for FAIL test
Listeners  SoftAsserts:   Screenshot: null   for FAIL
Selenide: 4.8
TestNG: 6.11

image

### PR DESCRIPTION
**Pull request by BorisOsipov**
## Proposed changes
Fix https://github.com/codeborne/selenide/issues/655 issue

## Checklist
- [x] Checkstyle and unit tests pass locally with my changes by running `gradle check chrome htmlunit` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by BorisOsipov** [comment]
It again complains about `WebDriverThreadLocalContainer.java` coverage decrease but it was not affected in the changes..

**Comment by BorisOsipov** [comment]
Yes it is. But some times it reports unexpected coverage changes here https://github.com/codeborne/selenide/blob/0f2e4502f85b3b46184373536309b2da0db956cb/src/main/java/com/codeborne/selenide/impl/WebDriverThreadLocalContainer.java#L41

and we can't fix it :)
Also I checked Codeconv documentation. It cannot exclude specific lines from coverage reports.

**Comment by rosolko** [comment]
@BorisOsipov Can you please try to replace foreach with stream if reduce this `if`:
```
ALL_WEB_DRIVERS_THREADS.stream()
  .filter(thread -> !thread.isAlive())
  .forEach(thread -> {
    log.info("Thread " + thread.getId() + " is dead. Let's close webdriver " + THREAD_WEB_DRIVER.get(thread.getId()));
    closeWebDriver(thread);
  });
``` 
Possible it can help avoid false codecov trigger.

**Comment by BorisOsipov** [comment]
@rosolko Let's make a separate issue about code coverage flashing and test your proposal?
I don't think such changes directly reference to this PR changes.

**Pull request merged**
