### PR TITLE
Add click command with relative position

### PR DESCRIPTION
**Pull request by cottonflop**
* Add a click method that takes an X and Y offset relative to the top left corner of the element

### CODE REVIEW

**Comment by cottonflop** [comment]
I'm not certain if any of the failing checks have to do with my changes?

**Comment by asolntsev** [comment]
@cottonflop I also don't understand pretty well. TravisCI doesn't show test reports :(

Trying to investigate it...

**Comment by asolntsev** [comment]
@cottonflop Your test fails in HtmlUnit:

```
om.gargoylesoftware.htmlunit.ScriptException: syntax error (script in http://127.0.0.1:15501/page_with_relative_click_position.html?browser=htmlunit&timeout=4000 from (30, 34) to (37, 12)#31)
```

**Comment by asolntsev** [comment]
@cottonflop Thank you! Merged.

**Comment by cottonflop** [comment]
No- thank you! :) I really appreciate your work here.

**Pull request merged**
