### PR TITLE
Fix screenshot concurency

### PR DESCRIPTION
**Pull request by jane-ryabchenko**
currentContextScreenshots and allScreenshots were replaced with ThreadLocal containers to make sure that each thread will work with own version of context and won't mess up the other thread's context or screenshots list.

### CODE REVIEW

**Comment by asolntsev** [comment]
@jane-ryabchenko It seems that the red build is just a glitch of Travis CI. The build is green on my private jenkins.

**Comment by jane-ryabchenko** [comment]
@asolntsev:

So what should we do in this situation?

Another question. Is there a way to see the test report pages generated 
during build on Travis CI?
I see the relative paths to them, but I don't see any option to 
view/download them

**Comment by asolntsev** [comment]
@jane-ryabchenko Can you rebase on master branch? We recently fixed this issue with TravisCI reports.

**Comment by jane-ryabchenko** [comment]
@asolntsev looks like there is some flakiness in tests. I don't see the way how my changes in ScreenShotLaboratory could have affected WebDriverThreadLocalContainer coverage.
https://codecov.io/gh/codeborne/selenide/compare/d9cf38b1f9c763ebbcead335781329ed19d46636...e12c4e865e30ed7ae857abe41f313e2e420ebf26/src/src/main/java/com/codeborne/selenide/impl/WebDriverThreadLocalContainer.java

Multithread tests are know for their flakiness though.

**Comment by asolntsev** [comment]
@jane-ryabchenko Thank you! Merged. Sorry for the long delay.

**Pull request merged**
